runtime: python37

handlers:
  - url: /
    upload: public/index.html
    expiration: "1s"
    http_headers:
      X-Frame-Options: DENY
    static_files: public/index.html
    secure: always

  - url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|json|js|map|webmanifest|css))
    static_files: public/\1
    upload: public/(.*\.(bmp|gif|ico|jpeg|jpg|png|json|js|map|webmanifest|css))
    expiration: "100d"
    secure: always

  - url: /(.+)
    static_files: public/\1/index.html
    upload: public/(.+)/index.html
    http_headers:
      X-Frame-Options: DENY
    expiration: "1s"
    secure: always
