name: Build and Deploy to App Engine

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - deployment

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up npm
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "275.0.0"
          service_account_email: ${{ secrets.GC_EMAIL }}
          service_account_key: ${{ secrets.GC_KEY}}

      - name: Auth
        run: |
          gcloud auth configure-docker

      - uses: actions/cache@v1
        with:
          path: ~/.cache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install npm
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Deploy
        run: |
          gcloud app deploy --project hatchways-volunteer
